const PlayersSource = [
  {
    id: 0,
    name: "Calvin",
    type: "pc",
    image: "https://i.pravatar.cc/48?u=118836",
    activity: "inactive",
    condition: "",
    exhaustion: 0,
    level: 4,
    prof: "barbarian",
    race: "goliath",
    saves: {
      fail: 0,
      success: 0,
    },
    seat: 0,
    initiative: 0,
    round: 0,
    targeted: false,
  },
  {
    id: 1,
    name: "Mocha",
    type: "pc",
    image: "https://i.pravatar.cc/48?u=118836",
    activity: "inactive",
    condition: "",
    exhaustion: 0,
    level: 5,
    prof: "rogue",
    race: "tiefling",
    saves: {
      fail: 0,
      success: 0,
    },
    seat: 0,
    initiative: 0,
    round: 0,
    targeted: false,
  },
  {
    id: 2,
    name: "Jason",
    type: "pc",
    image: "https://i.pravatar.cc/48?u=118836",
    activity: "inactive",
    condition: "",
    exhaustion: 0,
    level: 4,
    prof: "wizard",
    race: "dwarf",
    saves: {
      fail: 0,
      success: 0,
    },
    seat: 0,
    initiative: 0,
    round: 0,
    targeted: false,
  },
  {
    id: 3,
    name: "Enemy 1",
    type: "npc",
    image: "https://i.pravatar.cc/48?u=118836",
    activity: "inactive",
    condition: "",
    exhaustion: 0,
    level: 7,
    prof: "",
    race: "",
    saves: {
      fail: 0,
      success: 0,
    },
    seat: 0,
    initiative: 0,
    round: 0,
    targeted: false,
  },
  {
    id: 4,
    name: "Enemy 2",
    type: "npc",
    image: "https://i.pravatar.cc/48?u=118836",
    activity: "inactive",
    condition: "",
    exhaustion: 0,
    level: 4,
    prof: "",
    race: "",
    saves: {
      fail: 0,
      success: 0,
    },
    seat: 0,
    initiative: 0,
    round: 0,
    targeted: false,
  },
  {
    id: 5,
    name: "Enemy 3",
    type: "npc",
    image: "https://i.pravatar.cc/48?u=118836",
    activity: "inactive",
    condition: "",
    exhaustion: 0,
    level: 3,
    prof: "",
    race: "",
    saves: {
      fail: 0,
      success: 0,
    },
    seat: 0,
    initiative: 0,
    round: 0,
    targeted: false,
  },
]

export default PlayersSource;